{{- if .Values.global.k8sRegistry }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}

      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
  type: ClusterIP
{{- end}}
