apiVersion: v1
data:
  {{ .Values.service.name }}.yaml: |
    server:
      addr: "0.0.0.0:{{ .Values.service.port }}"
      logLevel: {{ .Values.service.logLevel }}
    ratings:
      {{- if .Values.global.k8sRegistry}}
      endpoint: {{ printf "%s.%s.svc.cluster.local:%s" .Values.upstreamServices.ratings.endpoints .Values.global.namespace .Values.global.ratings}}
      {{- else}}
      endpoint: {{ printf "%s.%s.svc.cluster.local" .Values.upstreamServices.ratings.endpoints .Values.global.namespace}}
      {{- end}}
      enableXDS: {{ .Values.upstreamServices.ratings.enableXDS }}
      xdsAddr: {{ .Values.global.xdsAddr }}
      xdsAuth: {{ .Values.global.xdsAuth }}
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}

