apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
  name: {{ .Values.service.name }}-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.service.name }}
      app.kubernetes.io/name: {{ .Values.service.name }}
      version: v2
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/reviews.cm.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/instance: {{ .Values.service.name }}
        app.kubernetes.io/name: {{ .Values.service.name }}
        version: v2
        sidecar.mesh.io/lane: {{ .Values.global.v2lane }}
        sidecar.mesh.io/data-plane-mode: "kitex"
        sidecar.mesh.io/mse-namespace: {{ .Values.global.configNamespace }}
    spec:
      containers:
        - args:
            - {{ .Values.service.name }}
            - --config=config/{{ .Values.service.name }}.yaml
          env:
            - name: NACOS_ENV_USERNAME
              value: {{ .Values.global.nacosUsername }}
            - name: NACOS_ENV_PASSWARD
              value: {{ .Values.global.nacosPassward }}
            - name: REVIEWS_COLOR
              value: gray
            - name: serverAddr
              value: {{ .Values.global.nacosAddress }}
            - name: serverPort
              value: {{ .Values.global.nacosPort | quote}}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=v2
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.global.otel.endpoint }}
            - name: ENABLE_RATINGS
              value: "enable"
            - name: TZ
              value: Asia/Shanghai
            - name: METRICS_LOG_LEVEL
              value: err
            - name: CONSUL_HTTP_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          image: {{ .Values.global.image }}
          imagePullPolicy: Always
          name: server
          ports:
          - containerPort: {{ .Values.service.port }}
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
            - mountPath: /etc/mse/pod
              name: volc-mse-podinfo
      restartPolicy: Always
      serviceAccountName: default
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ .Values.service.name }}
          name: config-volume
        - downwardAPI:
            defaultMode: 420
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.labels
              path: labels
          name: volc-mse-podinfo

