apiVersion: v1
data:
  {{ .Values.service.name }}.yaml: |
    server:
      addr: "0.0.0.0:{{ .Values.service.port }}"
      logLevel: {{ .Values.service.logLevel }}
    ratings:
      endpoint: {{ printf "%s.%s.svc.cluster.local" .Values.upstreamServices.ratings.endpoints .Values.global.namespace}}
      enableXDS: {{ .Values.upstreamServices.ratings.enableXDS }}
      xdsAddr: {{ .Values.global.xdsAddr }}
      xdsAuth: {{ .Values.global.xdsAuth }}
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}

