service:
  name: ratings
  port: 8083

upstreamServices:
  ratings:
    endpoints: ratings.zls-public-default-group.svc.cluster.local:8083
    enableXDS: true

image: mse-cn-beijing.cr.volces.com/demo/bookinfo
