service:
  name: productpage
  port: 8081

image: mse-cn-beijing.cr.volces.com/demo/bookinfo

upstreamServices:
  reviews:
    endpoints: reviews
    #endpoints: reviews
    enableXDS: true
  details:
    endpoint: details
    #endpoint: details
    enableXDS: true

otel:
  endpoint: http://host.docker.internal:4317
